//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="GisService")]
public interface GisServiceSoap
{
    
    // CODEGEN: Generating message contract since element name owner from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRecord", ReplyAction="*")]
    UpdateRecordResponse UpdateRecord(UpdateRecordRequest request);
    
    // CODEGEN: Generating message contract since element name reason from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContiguousAcresRecord", ReplyAction="*")]
    UpdateContiguousAcresRecordResponse UpdateContiguousAcresRecord(UpdateContiguousAcresRecordRequest request);
    
    // CODEGEN: Generating message contract since element name reason from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContiguousAcresRecordReasonOnly", ReplyAction="*")]
    UpdateContiguousAcresRecordReasonOnlyResponse UpdateContiguousAcresRecordReasonOnly(UpdateContiguousAcresRecordReasonOnlyRequest request);
    
    // CODEGEN: Generating message contract since element name phone from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMissingWellRecord", ReplyAction="*")]
    UpdateMissingWellRecordResponse UpdateMissingWellRecord(UpdateMissingWellRecordRequest request);
    
    // CODEGEN: Generating message contract since element name GetWellIDsByCAResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWellIDsByCA", ReplyAction="*")]
    GetWellIDsByCAResponse GetWellIDsByCA(GetWellIDsByCARequest request);

    // CODEGEN: Generating message contract since element name GetDepthToRedbedByMeterResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetDepthToRedbedByMeter", ReplyAction = "*")]
    GetDepthToRedbedByMeterResponse GetDepthToRedbedByMeter(GetDepthToRedbedByMeterRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateRecordRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRecord", Namespace="http://tempuri.org/", Order=0)]
    public UpdateRecordRequestBody Body;
    
    public UpdateRecordRequest()
    {
    }
    
    public UpdateRecordRequest(UpdateRecordRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UpdateRecordRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double OBJECTID;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string owner;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string producer;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public int actualID;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public int actingID;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string cnty_prop;
    
    public UpdateRecordRequestBody()
    {
    }
    
    public UpdateRecordRequestBody(double OBJECTID, string owner, string producer, int actualID, int actingID, string cnty_prop)
    {
        this.OBJECTID = OBJECTID;
        this.owner = owner;
        this.producer = producer;
        this.actualID = actualID;
        this.actingID = actingID;
        this.cnty_prop = cnty_prop;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateRecordResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRecordResponse", Namespace="http://tempuri.org/", Order=0)]
    public UpdateRecordResponseBody Body;
    
    public UpdateRecordResponse()
    {
    }
    
    public UpdateRecordResponse(UpdateRecordResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UpdateRecordResponseBody
{
    
    public UpdateRecordResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateContiguousAcresRecordRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContiguousAcresRecord", Namespace="http://tempuri.org/", Order=0)]
    public UpdateContiguousAcresRecordRequestBody Body;
    
    public UpdateContiguousAcresRecordRequest()
    {
    }
    
    public UpdateContiguousAcresRecordRequest(UpdateContiguousAcresRecordRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UpdateContiguousAcresRecordRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double OBJECTID;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public int actualID;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public int actingID;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string reason;
    
    public UpdateContiguousAcresRecordRequestBody()
    {
    }
    
    public UpdateContiguousAcresRecordRequestBody(double OBJECTID, int actualID, int actingID, string reason)
    {
        this.OBJECTID = OBJECTID;
        this.actualID = actualID;
        this.actingID = actingID;
        this.reason = reason;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateContiguousAcresRecordResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContiguousAcresRecordResponse", Namespace="http://tempuri.org/", Order=0)]
    public UpdateContiguousAcresRecordResponseBody Body;
    
    public UpdateContiguousAcresRecordResponse()
    {
    }
    
    public UpdateContiguousAcresRecordResponse(UpdateContiguousAcresRecordResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UpdateContiguousAcresRecordResponseBody
{
    
    public UpdateContiguousAcresRecordResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateContiguousAcresRecordReasonOnlyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContiguousAcresRecordReasonOnly", Namespace="http://tempuri.org/", Order=0)]
    public UpdateContiguousAcresRecordReasonOnlyRequestBody Body;
    
    public UpdateContiguousAcresRecordReasonOnlyRequest()
    {
    }
    
    public UpdateContiguousAcresRecordReasonOnlyRequest(UpdateContiguousAcresRecordReasonOnlyRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UpdateContiguousAcresRecordReasonOnlyRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double OBJECTID;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string reason;
    
    public UpdateContiguousAcresRecordReasonOnlyRequestBody()
    {
    }
    
    public UpdateContiguousAcresRecordReasonOnlyRequestBody(double OBJECTID, string reason)
    {
        this.OBJECTID = OBJECTID;
        this.reason = reason;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateContiguousAcresRecordReasonOnlyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContiguousAcresRecordReasonOnlyResponse", Namespace="http://tempuri.org/", Order=0)]
    public UpdateContiguousAcresRecordReasonOnlyResponseBody Body;
    
    public UpdateContiguousAcresRecordReasonOnlyResponse()
    {
    }
    
    public UpdateContiguousAcresRecordReasonOnlyResponse(UpdateContiguousAcresRecordReasonOnlyResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UpdateContiguousAcresRecordReasonOnlyResponseBody
{
    
    public UpdateContiguousAcresRecordReasonOnlyResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateMissingWellRecordRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMissingWellRecord", Namespace="http://tempuri.org/", Order=0)]
    public UpdateMissingWellRecordRequestBody Body;
    
    public UpdateMissingWellRecordRequest()
    {
    }
    
    public UpdateMissingWellRecordRequest(UpdateMissingWellRecordRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UpdateMissingWellRecordRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double OBJECTID;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public int actualID;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public int actingID;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string phone;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string email;
    
    public UpdateMissingWellRecordRequestBody()
    {
    }
    
    public UpdateMissingWellRecordRequestBody(double OBJECTID, int actualID, int actingID, string phone, string email)
    {
        this.OBJECTID = OBJECTID;
        this.actualID = actualID;
        this.actingID = actingID;
        this.phone = phone;
        this.email = email;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateMissingWellRecordResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMissingWellRecordResponse", Namespace="http://tempuri.org/", Order=0)]
    public UpdateMissingWellRecordResponseBody Body;
    
    public UpdateMissingWellRecordResponse()
    {
    }
    
    public UpdateMissingWellRecordResponse(UpdateMissingWellRecordResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UpdateMissingWellRecordResponseBody
{
    
    public UpdateMissingWellRecordResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetWellIDsByCARequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWellIDsByCA", Namespace="http://tempuri.org/", Order=0)]
    public GetWellIDsByCARequestBody Body;
    
    public GetWellIDsByCARequest()
    {
    }
    
    public GetWellIDsByCARequest(GetWellIDsByCARequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetWellIDsByCARequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double CaObjectID;
    
    public GetWellIDsByCARequestBody()
    {
    }
    
    public GetWellIDsByCARequestBody(double CaObjectID)
    {
        this.CaObjectID = CaObjectID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetWellIDsByCAResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWellIDsByCAResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetWellIDsByCAResponseBody Body;
    
    public GetWellIDsByCAResponse()
    {
    }
    
    public GetWellIDsByCAResponse(GetWellIDsByCAResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetWellIDsByCAResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetWellIDsByCAResult;
    
    public GetWellIDsByCAResponseBody()
    {
    }
    
    public GetWellIDsByCAResponseBody(string GetWellIDsByCAResult)
    {
        this.GetWellIDsByCAResult = GetWellIDsByCAResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetDepthToRedbedByMeterRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDepthToRedbedByMeter", Namespace = "http://tempuri.org/", Order = 0)]
    public GetDepthToRedbedByMeterRequestBody Body;

    public GetDepthToRedbedByMeterRequest()
    {
    }

    public GetDepthToRedbedByMeterRequest(GetDepthToRedbedByMeterRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetDepthToRedbedByMeterRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
    public int meterInstallationID;

    public GetDepthToRedbedByMeterRequestBody()
    {
    }

    public GetDepthToRedbedByMeterRequestBody(int meterInstallationID)
    {
        this.meterInstallationID = meterInstallationID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetDepthToRedbedByMeterResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDepthToRedbedByMeterResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public GetDepthToRedbedByMeterResponseBody Body;

    public GetDepthToRedbedByMeterResponse()
    {
    }

    public GetDepthToRedbedByMeterResponse(GetDepthToRedbedByMeterResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetDepthToRedbedByMeterResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public string GetDepthToRedbedByMeterResult;

    public GetDepthToRedbedByMeterResponseBody()
    {
    }

    public GetDepthToRedbedByMeterResponseBody(string GetDepthToRedbedByMeterResult)
    {
        this.GetDepthToRedbedByMeterResult = GetDepthToRedbedByMeterResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface GisServiceSoapChannel : GisServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GisServiceSoapClient : System.ServiceModel.ClientBase<GisServiceSoap>, GisServiceSoap
{
    
    public GisServiceSoapClient()
    {
    }
    
    public GisServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GisServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GisServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GisServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateRecordResponse GisServiceSoap.UpdateRecord(UpdateRecordRequest request)
    {
        return base.Channel.UpdateRecord(request);
    }
    
    public void UpdateRecord(double OBJECTID, string owner, string producer, int actualID, int actingID, string cnty_prop)
    {
        UpdateRecordRequest inValue = new UpdateRecordRequest();
        inValue.Body = new UpdateRecordRequestBody();
        inValue.Body.OBJECTID = OBJECTID;
        inValue.Body.owner = owner;
        inValue.Body.producer = producer;
        inValue.Body.actualID = actualID;
        inValue.Body.actingID = actingID;
        inValue.Body.cnty_prop = cnty_prop;
        UpdateRecordResponse retVal = ((GisServiceSoap)(this)).UpdateRecord(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateContiguousAcresRecordResponse GisServiceSoap.UpdateContiguousAcresRecord(UpdateContiguousAcresRecordRequest request)
    {
        return base.Channel.UpdateContiguousAcresRecord(request);
    }
    
    public void UpdateContiguousAcresRecord(double OBJECTID, int actualID, int actingID, string reason)
    {
        UpdateContiguousAcresRecordRequest inValue = new UpdateContiguousAcresRecordRequest();
        inValue.Body = new UpdateContiguousAcresRecordRequestBody();
        inValue.Body.OBJECTID = OBJECTID;
        inValue.Body.actualID = actualID;
        inValue.Body.actingID = actingID;
        inValue.Body.reason = reason;
        UpdateContiguousAcresRecordResponse retVal = ((GisServiceSoap)(this)).UpdateContiguousAcresRecord(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateContiguousAcresRecordReasonOnlyResponse GisServiceSoap.UpdateContiguousAcresRecordReasonOnly(UpdateContiguousAcresRecordReasonOnlyRequest request)
    {
        return base.Channel.UpdateContiguousAcresRecordReasonOnly(request);
    }
    
    public void UpdateContiguousAcresRecordReasonOnly(double OBJECTID, string reason)
    {
        UpdateContiguousAcresRecordReasonOnlyRequest inValue = new UpdateContiguousAcresRecordReasonOnlyRequest();
        inValue.Body = new UpdateContiguousAcresRecordReasonOnlyRequestBody();
        inValue.Body.OBJECTID = OBJECTID;
        inValue.Body.reason = reason;
        UpdateContiguousAcresRecordReasonOnlyResponse retVal = ((GisServiceSoap)(this)).UpdateContiguousAcresRecordReasonOnly(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateMissingWellRecordResponse GisServiceSoap.UpdateMissingWellRecord(UpdateMissingWellRecordRequest request)
    {
        return base.Channel.UpdateMissingWellRecord(request);
    }
    
    public void UpdateMissingWellRecord(double OBJECTID, int actualID, int actingID, string phone, string email)
    {
        UpdateMissingWellRecordRequest inValue = new UpdateMissingWellRecordRequest();
        inValue.Body = new UpdateMissingWellRecordRequestBody();
        inValue.Body.OBJECTID = OBJECTID;
        inValue.Body.actualID = actualID;
        inValue.Body.actingID = actingID;
        inValue.Body.phone = phone;
        inValue.Body.email = email;
        UpdateMissingWellRecordResponse retVal = ((GisServiceSoap)(this)).UpdateMissingWellRecord(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetWellIDsByCAResponse GisServiceSoap.GetWellIDsByCA(GetWellIDsByCARequest request)
    {
        return base.Channel.GetWellIDsByCA(request);
    }
    
    public string GetWellIDsByCA(double CaObjectID)
    {
        GetWellIDsByCARequest inValue = new GetWellIDsByCARequest();
        inValue.Body = new GetWellIDsByCARequestBody();
        inValue.Body.CaObjectID = CaObjectID;
        GetWellIDsByCAResponse retVal = ((GisServiceSoap)(this)).GetWellIDsByCA(inValue);
        return retVal.Body.GetWellIDsByCAResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDepthToRedbedByMeterResponse GisServiceSoap.GetDepthToRedbedByMeter(GetDepthToRedbedByMeterRequest request)
    {
        return base.Channel.GetDepthToRedbedByMeter(request);
    }

    public string GetDepthToRedbedByMeter(int meterInstallationID)
    {
        GetDepthToRedbedByMeterRequest inValue = new GetDepthToRedbedByMeterRequest();
        inValue.Body = new GetDepthToRedbedByMeterRequestBody();
        inValue.Body.meterInstallationID = meterInstallationID;

        GetDepthToRedbedByMeterResponse retVal = ((GisServiceSoap)(this)).GetDepthToRedbedByMeter(inValue);
        return retVal.Body.GetDepthToRedbedByMeterResult;
    }
}
